### PR TITLE
Additional Quality and Codec Possibilities

### PR DESCRIPTION
**Pull request by Hiltronix**
Added 720p and 1080p to quality.
Added space as an option to period for H.264, X.265 to be represented as H 264, X 265.  I personally don't like it, but it's now common in torrent names.
Added HEVC to codecs, as it's a technical alternate name for h.265, and popular in torrent names.

### CODE REVIEW

**Comment by roidayan** [comment]
Which torrent name has spaces in x264 x265? Can you give an example? I think some sites replace dots to spaces in the torrent names but the original name will probably won't have spaces.

**Comment by Hiltronix** [comment]
Then I guess what I'm seeing is that some sites are replacing all periods with spaces when displaying titles.

**Comment by Hiltronix** [comment]
I updated the PR to only adding HEVC to codec.

**Comment by roidayan** [comment]
your change breaks all tests. did you check it?
beside the tests. I can't really find torrent names with hevc but without x265 or h265. I see they always appear both. can you give an example? I think in the past there was only a single group with hevc and didn't specify h265 or x265. but it's 1 group from hundreds.

**Comment by Hiltronix** [comment]
Do do find it that it shows up on it's own often enough to be an issue.  But that's fine.  I'm not interested in debating the issue.  I'll fork and add it myself.  Thanks for the work and sharing the project.

**Comment by roidayan** [comment]
I'm just trying to help. Note I'm not the owner of the project. just a contributor like you.
If all tests failed then maybe your match worked for the single tests you checked but all others failed.
By looking at your change it looks like your regex was incorrect as you added hevc outside the group bracket.
You added  '(xvid|[hx]\.?26[45])|HEVC'
I think it should probably by  '(xvid|[hx]\.?26[45]|HEVC)'
You can run manually the tests to make sure nothing breaks.

**Pull request closed without merging**
